cqerl/cqerl

src/cqerl.app.src

Add re2 as app dependency in cqerl.app.src. This is needed for generating releases that depend on cqerl.

Add re2 in cqerl.app.src

---

src/cqerl.app.src

Otherwise, applications that use this one and want to generate a release will have to manually include the dependencies.

Include dependencies in .app file

---

src/cqerl.erl

A combination of inspection and experimentation turned up a couple of valid return types for `cqerl:new_client` which weren't covered by the spec (and therefore caused dialyzer errors when I tried to handle them).

Add additional valid return types to new_client

---

README.md
include/cqerl.hrl
include/cqerl_protocol.hrl
src/cqerl.erl
src/cqerl_protocol.erl
test/cqerl_protocol_tests.erl
test/integrity_SUITE.erl

This is a simple change to the API that makes in a little cleaner IMO. In addition to the `?CQERL_CONSISTENCY_*` and `?CQERL_BATCH_*` constants, the API now accepts atoms (i.e., `any`, `one`, `two`, etc). While the API is documented as taking the atoms, it will also take the old integer values as well. This should not break any existing uses of the API, but provides a nice new option.

Use atoms for consistency and batch mode settings

---

README.md

Tiny addition to the documentation to note the method of binding a `LIMIT` variable

Update doc to include variable LIMIT value binding

---

include/cqerl.hrl

Maps are now a valid type for query values. This change notifies dialyzer of the fact.

Add maps:map() to valid types for #cql_query.values

---

include/cqerl.hrl
src/cqerl_client.erl
src/cqerl_protocol.erl

Couple of fixes here: First, my earlier addition of the `maps:map()` type should just have been `map()`. Also the `gen_tcp:socket()` type isn't exported, so I've changed that so that it doesn't trip dialyzer up. (I'll submit a separate patch to OTP to get that exported).
The bigger fix, though, is that empty maps weren't working as query values when there were no columns specified in a query. This change fixes that up.

Empty map values and dialyzer fixes

---

src/cqerl_datatypes.erl

When the `maps` option is set, map fields were still being returned as proplists due to a typo.

Fix bug in map return type

---

src/cqerl.erl
src/cqerl_client.erl
test/integrity_SUITE.erl
test/load_SUITE.erl

So this one is going to take a bit of explaining, and I don't necessarily expect you to accept it in its current form - as much as anything I just want to get some thoughts and feedback.
The initial problem I set out to solve is this: When you call `cqerl:new_client` with an invalid keyspace, you get back `{closed, {server_error, ..., ...}`, because the server booted the connection before `cqerl_client` got into the `live` state. That's fine and as it should be. What I noticed while writing some unit tests, though, is that if you call `cqerl:new_client` again with the same invalid keyspace, you'll get a `gen_server:call` timeout (and crash).
Digging into the problem, it can be traced down to the way that `cqerl:new_client` works. Most notably, it calls `cqerl_client:new_user/2` after …

Fix client startup race

---

src/cqerl.erl
src/cqerl_datatypes.erl
src/cqerl_protocol.erl
test/integrity_SUITE.erl

This change adds the ability to specify `text_uuids` as an application option (a la `maps`) to receive `uuid` and `timeuuid` columns as canonical-form UUID strings (in binary) rather than pure binaries.
It also cleans up some of the handling of the maps option so that future options will be able to be added more easily.

Add text_uuids option

---

include/cqerl_protocol.hrl
src/cqerl_batch.erl
src/cqerl_batch_sup.erl
src/cqerl_cache.erl
src/cqerl_client.erl
test/integrity_SUITE.erl

Previously the evicted query error (0x2500 / 9472) would propagate back
up to the caller. That's not much use, though, because they can't force
cqerl to empty its list of prepared queries (and nor should they have
to). Instead, we now flush out the cache item and start over with it
unprepared.
For batch queries, we flush all involved queries since it's a bit fiddly
(and potentially error prone) to try to figure out which query has
failed.
I also cleaned up a few unused fields and tighted a couple of type
specs.

Recover from error when prepared query has been evicted

---

src/cqerl.erl

At shutdown there are sometimes crashes as some code somewhere is trying to check connections into a pool that is no longer alive. Removing pools in the terminate handler resolves this issue.

Prevent crashes at shutdown by cleaning up pools

---

README.md
src/cqerl.erl
src/cqerl_app.erl
src/cqerl_client.erl
src/cqerl_client_sup.erl
src/cqerl_hash.erl
src/cqerl_sup.erl
test/hash_SUITE.erl
test/integrity_SUITE.erl
test/load_SUITE.erl
test/test_helper.erl

NOTE: This isn't intended to be merged yet - I still need to add some docs and further ct tests. The core functionality, however, is done and I figured I'd share it to get any input you (@matehat) or anyone else has before getting too far along.
A note on terminology: When I say "client" I mean a `cqerl_client` process. When I say "user" I mean any process in an application that calls `cqerl:get_client` or `cqerl:new_client` to get a client to use to make a query.
So - we've been having a few intermittent problems with the existing pooler-based implementation. Fundamentally, it doesn't seem to be an ideal choice for managing a pool of clients where each client can have multiple users, as is the case with cqerl clients. Additionally, as has been noted in #49, it has scalability issues with …

Add 'hash' client allocation mode

---

README.md
include/cqerl.hrl
include/cqerl_protocol.hrl
src/cqerl.erl
src/cqerl_client.erl
src/cqerl_client_sup.erl
src/cqerl_processor.erl
src/cqerl_processor_sup.erl
src/cqerl_protocol.erl
test/integrity_SUITE.erl
test/test.config
test/test_helper.erl

Fix #63
@bernardd what do you think?
Basically, this means that to use this client library with a 2.1.x Cassandra instance, one needs to set the `protocol_version` application parameter to `3`, or provide it in the client options.

Add support for native protocol v3

---

src/cqerl_client.erl

@matehat here's another one we had to add to our fork a while back due to this error:
```erlang
{failed,
{'EXIT',
{badmatch,
{error,
{{case_clause,
<<"UPDATE ...my cql query here...">>},
[{cqerl_client,dequeue_query,1,
[{file,"src/cqerl_client.erl"},{line,566}]},
{cqerl_client,release_stream_id,2,
[{file,"src/cqerl_client.erl"},{line,605}]},
{cqerl_client,handle_info,3,
[{file,"src/cqerl_client.erl"},{line,418}]},
{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]},
{proc_lib,init_p_do_apply,3,
[{file,"proc_lib.erl"},{line,240}]}]}}}}}
```

Fix case_clause bug when a prepare gets dequeued

---

src/cqerl_datatypes.erl

It allows to let unnecessary fields be empty when binding a user define type column

Add default null for encode {udt, Types}

---

src/cqerl.erl
src/cqerl_client.erl
src/cqerl_client_sup.erl
src/cqerl_cluster.erl
src/cqerl_hash.erl

@toland noticed that, as a side-effect of passing credentials into client processes via a supervisor start, they ended up being logged by the supervisor. Obviously, generally speaking, logging passwords is Bad.
Turned out the fix was a bit complicated, since auth data was actually passed through in two parameters - the `Opts` and the `Key`.
After a few different attempts, I fixed the `Opts` issue by passing through the `OptsGetter` function and calling that from within the client. Even though the fun still effectively encapsulates the data, it doesn't show up in the log.
The key was a bit more fiddly since it's passed around and used interchangeably with the `{Node, Opts}` tuple it actually is. That meant that simply taking the auth data out of the Key would potentially break other bits, …

Prevent authentication credentials from being logged

---

rebar.config

Replaced the old commit hash with the new commit hash which has the added support for erlang 19.

Added new commit hash for snappy

---

include/cqerl_protocol.hrl
src/cqerl_batch.erl
src/cqerl_batch_sup.erl
src/cqerl_cache.erl
src/cqerl_client.erl
src/cqerl_processor.erl
src/cqerl_processor_sup.erl

It turns out that C* prepared queries are cached per node and not
discarded when the requesting connection is dropped (but rather only
when the node is restarted or they are cycled out of the cache). That
means we can shrink the size of our prepared query cache so that it only
holds at most one copy of each query per node (with the side benefit of
also only needing to prepare each query once per node).
This also has the benefit of working around the C* bug described at
https://issues.apache.org/jira/browse/CASSANDRA-10786, since we only
cache the query once and remove that instance from the cache if we get
'unprepared'.

Change prepared query cache to be per-node rather than per-client

---

src/cqerl.erl

Since both `send_query` and `run_query` internally work the same when comes to processing arguments, those functions should have same argument specification. This PR adds `#cql_query_batch{}` to the specification of `send_query` to match `run_query` spec.

Fix cqerl:send_query spec

---

rebar.config

This PR updates `rebar.config` with new `snappy` version, that includes fix which makes Mac users' life easier.

Use more recent snappy

---

src/cqerl_cluster.erl

add_nodes/1,2,3 was previously async, but were changed to use gen_server:call
instead to prevent a race condition (#111). That change did however introduce
the possibility of gen_server timing out before the add_to_cluster handler had
completed.
This commit introduces an application env variable that makes it possible to
specify the timeout, and sets it to 30 seconds if not specified.

Add timeout to add_nodes/1,2,3 gen_server calls

---

rebar.config

Currently, cqex fails on Elixir 1.4.x/OTP 19 due to an outdated dependency on lz4. This PR bumps lz4 to make everything work again.

Update lz4 to new release 0.2.4

---

rebar.config

When trying to compile an empty Elixir project with only cqerl as dependency and using Erlang/OTP 20, I get this
```
➜  test iex -S mix
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
===> Compiling pooler
===> Compiling src/pooler.erl failed
src/pooler.erl:60: export_all flag enabled - all functions will be exported
** (Mix) Could not compile dependency :pooler, "/home/rbino/.mix/rebar3 bare compile --paths "/tmp/test/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile pooler", update it with "mix deps.update pooler" or clean it with "mix deps.clean pooler"
```
Bumping `pooler` to 1.5.2 fixes this problem.

Update pooler to 1.5.2

---

rebar.config

This version tries to fetch dependency from Github, if possible. It is a great help for developers in China, where Google is blocked.

Bump re2 version to 1.7.5

---

src/cqerl_batch.erl

In case of a failed preparation for a batch, the message notifying about this issue would be lost, because the tuple contains 3 elements, not 2.

Fix expected message format for the preparation_failed notification

---

src/cqerl.erl
src/cqerl_cluster.erl
test/cqerl_datatypes_tests.erl

- replace `crypto:rand_bytes/1`, which is gone in OTP 20 (it's used in the eunit tests)
- replace `random:uniform/1`, which is deprecated in OTP 20
The remaining warnings from OTP 20 that I see are about upgrading `cqerl_client` from `gen_fsm` to `gen_statem`.

OTP 20 function call changes

---

src/cqerl_client.erl

When using TLS/SSL the client does not handle the 'ssl_closed' event. When the connection to the server is broken (for instance, due to the server restarting) the client ends up in a kind of zombie state. The clients never fail, are never restarted, and all queries end up hitting the FSM timeout.

Changed client so that it handles ssl_closed events

---

src/cqerl.erl

Avoid crashing when calling `head/2` with some options on an empty result

Handle empty_dataset also in head/2

---

src/cqerl_protocol.erl
test/cqerl_protocol_tests.erl

As per documentation https://docs.datastax.com/en/cassandra-oss/2.2/cassandra/dml/dmlConfigConsistency.html both `LOCAL_SERIAL` and `SERIAL` are allowed levels for `CONSISTENCY` doing Read operations (to make sure read is done after all pending writes in LWT). 
Currently there's a workaround to use integer instead of atom, but this is nice QoL change ;)

Allow local_serial/serial consistencies for read consistency.
